### ISSUE TITLE
Analyse the GitHub classroom functionality

### ISSUE THREAD

**Issue by pmhsfelix** [i-on-project/codegarten#1]
- Go through the following documentation: https://github.blog/2020-03-18-set-up-your-digital-classroom-with-github-classroom/
- Create a GitHub testing organization (e.g. `i-on-project-codegarten-tests`) and perform some of the steps in the previous guide, both in the teacher and student role.

**Comment by TiagoMMDavid** [comment]
Done!
Created organization: https://github.com/i-on-project-codegarten-tests
Created classroom: https://classroom.github.com/classrooms/80703382-i-on-project-codegarten-test-classroom
Created assignment: https://classroom.github.com/classrooms/80703382-i-on-project-codegarten-test-classroom/assignments/test-assignment-1
