### ISSUE TITLE
Define authentication and access token architecture

### ISSUE THREAD

**Issue by pmhsfelix** [i-on-project/codegarten#10]
- Codegarten API access - Design how a user authenticates via the client app and obtains an access token to use the CodeGarten API.

- GitHub API access - Design how the CodeGarten back-end obtains access tokens representing authorisations delegated by the user.

- What is the difference between a GitHub app and an OAuth app.

**Comment by PTKay** [comment]
So far we have researched about the differences between OAuth Apps and GitHub Apps. Those are documented [here](https://github.com/i-on-project/codegarten/blob/docs/gh-10-auth-and-access-tokens/docs/auth/app-comparison.md). 

To better understand how to work with a GitHub App, we have developed a [simple test application](https://github.com/i-on-project-codegarten-tests/GitHubApp-Test) using Node.js that lists organizations (that have the app installed), lists its repositories and creates a test repository in the chosen organization.

Using what's described above, we're currently thinking about using a GitHub App in CodeGarten.

We will now start discussing about the API access.
