### ISSUE TITLE
[API] Leave classroom functionality

### ISSUE THREAD

**Issue by dvsshadow** [i-on-project/codegarten#41]
Currently, there are two functionalities related to leaving a classroom and an assignment that are not yet implemented:
- A student should be allowed to leave a classroom ~~and an assignment~~
- A teacher should be able leave a classroom **ONLY** if there are more teachers in the classroom, otherwise the only option is to delete the classroom

**Comment by TiagoMMDavid** [comment]
My bad! I thought the issue was about leaving an assignment functionality and so I closed it 😅
