### ISSUE TITLE
Research and do a small example using JDBI's fluent API

### ISSUE THREAD

**Issue by pmhsfelix** [i-on-project/codegarten#8]
Research and do a small example using [JDBI's fluent API](https://jdbi.org/#_fluent_api).
The main goal is to gain familiarity with this way of interacting with RDBMS that support JDBC.

**Comment by dvsshadow** [comment]
JDBI example repo available [here](https://github.com/i-on-project-codegarten-tests/JDBI-Test).

**Comment by pmhsfelix** [comment]
Just saw the examples in the repo 👍
